<a href="https://colab.research.google.com/github/megumihoshino/Basic-Java-Script-/blob/main/ML_modelpractice1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#implementation tensorflow and keras
import tensorflow as tf

mnist = tf.keras.datasets.fashion_mnist #dataset fashion mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0 #

model  = tf.keras.models.Sequential([ #buat arsitektur MLP, definisi layer2
    tf.keras.layers.Flatten(input_shape = (28,28)), #input
    tf.keras.layers.Dense(512, activation = tf.nn.relu), #hidden
    tf.keras.layers.Dense(10, activation = tf.nn.softmax) #ouput/dense layer
])

model.compile(optimizer = tf.optimizers.Adam(),#optimizer
              loss = 'sparse_categorical_crossentropy', #klasifikasi 3 kls atau lbh
              metrics = ['accuracy'])

model.fit(x_train, y_train, epochs = 10)  #jml brp kli model kita melakukan back propagation

4422102/4422102 [==============================] - 0s 0us/step
Epoch 1/10
1875/1875 [==============================] - 22s 11ms/step - loss: 0.4738 - accuracy: 0.8316
Epoch 2/10
1875/1875 [==============================] - 18s 10ms/step - loss: 0.3588 - accuracy: 0.8683
Epoch 3/10
1875/1875 [==============================] - 18s 10ms/step - loss: 0.3231 - accuracy: 0.8802
Epoch 4/10
1875/1875 [==============================] - 18s 9ms/step - loss: 0.2992 - accuracy: 0.8889
Epoch 5/10
1875/1875 [==============================] - 19s 10ms/step - loss: 0.2795 - accuracy: 0.8954
Epoch 6/10
1875/1875 [==============================] - 18s 10ms/step - loss: 0.2644 - accuracy: 0.9016
Epoch 7/10
1875/1875 [==============================] - 17s 9ms/step - loss: 0.2545 - accuracy: 0.9054
Epoch 8/10
1875/1875 [==============================] - 18s 10ms/step - loss: 0.2415 - accuracy: 0.9100
Epoch 9/10
1875/1875 [==============================] - 19s 10ms/step - loss: 0.2306 - accuracy: 0.9129
Epo

In [ ]:
#PRA PEMROSESAN DATA UTK MODEL
'''
1. ubah dataset ke dlm btk larik/array
2. pisah atribut dan label pd data
3. lakukan normalisasi (mengubah skala data mjd skala yg seragam)
4. lakukan train data dan test data
'''

#PEMROSESAN DATA GBR
'''
- utk versi TF <=2.9, bisa lakukan augmentasi menggunakan fungsi
ImageDataGenerator utk data latih dan data validasi.
- utk versi TF >2.9, bisa menggunakan tf.data dan layer augmentasi
scr lngsng pd layer sequentials
'''

#data augmentasi, TF <=2.9
'''
- ImageDataGenerator = fungsi utk mempersiapkan data latih dan data
validasi
- Augmentasi gbr = teknik utk memperbyk data latih dg cara duplikasi
gbr yg telah ada (rescale, rotation, shear, zoom, dst)
'''


In [ ]:
#kode augmentasi gambar, TF <=2.9
train_datagen = ImageDataGenerator(
    rescale = 1./255,
    rotation_range = 40,
    width_shift_range = 0.2,
    height_shift_range = 0.2,
    shear_range = 0.2,
    zoom_range = 0.2,
    fill_mode = 'nearest',
    horizontal_flip = 'True')

test_datagen = ImageDataGenerator(rescale = 1./255)

In [ ]:
#KODE AUGMENTASI JIKA TF>2.9

#mengubah ukuran gbr dan pixel scr eksplisit
IMG_size = 180

resize_and_rescale = tf.keras.Sequential([
    layers.Resizing(IMG_size, IMG_size),
    layers.Rescaling(1.0/255)
])

#fungsi augmentasi
data_augmentation = tf.keras.Sequential([
    layers.RandomFlip("horizontal_and_vertical"),
    layers.RandomRotation(0.2),
])

#menerapkan data augmentasi
'''
pd proses ini kita memasukkan data augmentasi tsb pd layer sequentials
ketika membangung struktur neural network agar seluruh dataset
yg ada dpt diproses dan bs melakukan pelatihan dg baik.
'''

model = tf.keras.Sequential([
    #menambahkan processing image yg telah didefinisikan
    resize_and_rescale,
    data_augmentation,
    layers.Conv2D(16,3, padding='same', activation='relu'),
    layers.MaxPooling2D(),
    #kita menyesuaikan sisa layer dg kasus yg dimiliki
])


In [ ]:
#HAL PENTING DLM MEMBANGUN MODEL NEURAL NETWORK DG TF > 2.9
'''
1. device
  data augmentasi akn berjln pd device yg digunakan, baik cloud
  environment maupun lokal. proses ini akn berjln scr bersamaan
  dg eksekusi layer lainnya. hal ini menyebabkan komputasi yg dilakukan
  akn lbh berat shg penggunaan GPU akn lbh menguntungkan.

2. ekspor model
  ketika mengekspor model menggunakan model.save, layer processing
  akn disimpan bersm dg layer lainnya. jika menggunakan model ini,
  maka akn scr otomatis menstandarkan gbr (sesuai konfigurasi layer)
  hal ini dpt membantu utk implementasi ulang logika tsb di sisi server.

3. data augmentasi tdk akn aktif pd saat pengujian shg gbr input
  akn ditmbh slm pemanggilan model.fit (bkn model.evaluate atau
  model.predict)
'''

In [ ]:
#PEMROSESAN DATA BAHASA
#CTH KODE

from tensorflow.keras.preprocessing.text import Tokenizer

sentences = ["I LOVE MY HUSBANDO TSUKISHIMA KEI"]

tokenizer = Tokenizer(num_words = 100)
#tokenizer berfungsi utk membangun indeks kata dari korpus kata

tokenizer.fit_on_texts(sentences)
sequences = tokenizer.texts_to_sequences(sentences)
#text_to_sequences utk konversi teks mjd urutan numerik berdsrkan kamus yg dibuat

print(tokenizer.word_index)
print(sequences)

{'i': 1, 'love': 2, 'my': 3, 'husbando': 4, 'tsukishima': 5, 'kei': 6}
[[1, 2, 3, 4, 5, 6]]


In [ ]:
#PEMROSESAN DATA BAHAS 2.0
#CTH KODE
'''
dlm pemrosesan data bhs kita menggunakan fungsi texts_to_sequences yg berguna
utk mengonversi teks mjd urutan indeks numerk berdsrkan kamus yg dibuat.

namun, kondisi tsb msh ringkih dan performanya blm ckp baik krn btk dari data yg dimiliki
msh beragam dan terbatas pd kata2 yg tdk termasuk dlm dataset. hal tsb bisa diatasi
dg fungsi oov_token dan padding shg dataset memiliki shape yg serupa.

- pd kasus ini, oov_token berguna utk mengatasi kata yg tdk termsk pd tokenizer shg akn
diubah mjd spesial value yg bs kita tentukan sendiri.
'''


In [ ]:
#CTH KODE penggunaan oov_token dan texts_to_sequences serta padding

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
sentences = ["Tsukishima Kei",
              "A smart middle blocker from Karasuno."]


tokenizer = Tokenizer(num_words = 100, oov_token = "<OOV>")
tokenizer.fit_on_texts(sentences)
sentences = ["Tsukishima Kei",
             "A smart middle blocker from Karasuno.",
             "Kei is Karasuno's volleyball member",
             "Do you think he is cute? Isn't he?"]

sequences = tokenizer.texts_to_sequences(sentences)

padded = pad_sequences(sequences, maxlen = 10, truncating = "post", padding = "post" )

print("Tokenizer: ", tokenizer.word_index)
print("Sequences:", sequences)
print("Padded: ", padded)

#dalam cth kode di atas, pada kata yg tidak termasuk akan diberi nilai "1" dalam hal ini akan diproses dengan kata "<OOV>"

Tokenizer:  {'<OOV>': 1, 'tsukishima': 2, 'kei': 3, 'a': 4, 'smart': 5, 'middle': 6, 'blocker': 7, 'from': 8, 'karasuno': 9}
Sequences: [[2, 3], [4, 5, 6, 7, 8, 9], [3, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1]]
Padded:  [[2 3 0 0 0 0 0 0 0 0]
 [4 5 6 7 8 9 0 0 0 0]
 [3 1 1 1 1 0 0 0 0 0]
 [1 1 1 1 1 1 1 1 0 0]]


In [ ]:
#MENGGUNAKAN MODEL UTK MELAKUKAN PREDIKSI

'''
kita bisa menggunakan API Keras utk membuat model yg sudah dibuat
membuat program ML prediksi dg mudah dan cepat
'''
#CTH KODE

import tensorflow as tf
import numpy as np
from tensorflow import keras
#merubah angka2 mjd sebuah larik/array agar mudah diterima oleh Keras

x = np.array([-3.5, -2.5, -1.5, -1, 0, 1.5, 2.5, 3.5, 4.5, 5.0], dtype = float)
y = np.array([6.0, 7.0, 8.0, 9.0, 9.0, 10.0, 11.0, 12.0], dtype = float)

#buat model neural network  dg memanggil fungsi tf.keras.Sequential()

model = tf.keras.Sequential([
    tf.keras.layer.Dense(units = 1, input_shape = [1])
])

In [ ]:
'''
parameter?
pada cth kode di atas, terdpt parameter units dan input_shape.
- parameter units:
  parameter units dari fungsi tf.keras.Dense() adlh jlm perceptron yg dimiliki
  olh layer tsb. yg perlu diperhatikan, mdodel sequential adlh layer pertama dr model
  tsb adlh hrs memiliki parameter input_shape agar model bs mengenali btk input yg akn
  diproses.

  - parameter input_shape
    parameter ini adlh btk dr tiap elemen input yg akn diterima dr model. pd kasus ini
    tiap elemen dr data adlh sebuah bil. numerik 1 digit, shg input_shape dpt
    diisi dg angka 1. jika sebuah elemen dr datset kita berupa gbr yg memiliki
    dimensi 32*32 pixel, maka input_shape dpt diisi dg angka [32*32]
'''

In [ ]:
'''
fungsi kerugian (loss function)
- adalah sebuah metrik yg digunakan dlm machne learning utk evaluasi sbrp
baik sebuah model utk prediksi target pd data training.
bbrp cth loss function yaitu:
- mean_squared_error -> utk mslh regresi
- binary_crossentropy -> utk klasifikasi biner
- categorical_crossentropy -> utk klasifikasi multi kelas

utk implementasi optimizer dan loss function pke TF, bs pakai fungsi ini:
model.compile()
'''
#cth
model.compile(optimizer = "sgd", loss = "mean_squared_error")

#fungsi fit dlm ML
'''
fungsi fit dlm machine learning berguna agar model dpt mempelajari
hubungan antara atribut dan label pd dataset.

epochs adalah banyaknya yg dibutuhkan oleh sebuah model NN hrs belajar
utk memperbaiki akurasinya.'''

#cth fungsi epochs
model.fit(x,y, epochs = 500)

'''
utk bbrp kasus nilai epochs yg bsr belum tentu meningkatkan nilai akurasi.
bs saja loss yg didpt stagnan atau malah semakin besaar. oleh krn itu
kita perlu melakukan trial dan eror utk memperhatikan loss yg didpt ketika
melakukan pelatihan.'''
